INVALID_YAML = 1
CONFIG_NOT_FOUND = 2
WRONG_VERBOSITY_CONFIG = 3
INVALID_REFRESH_RATE_VAL = 4
REFRESH_RATE_NOT_FOUND = 5
NO_OUTPUT_FOUND = 6
KAFKA_BROKER_NOT_FOUND = 7
SOURCES_CLASSES_CREATION_ERROR = 8
